"""password textcol 20 to textcol 200.

Revision ID: 70e71bace69a
Revises: 71e8ce0fb927
Create Date: 2023-10-07 21:30:44.847982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e71bace69a'
down_revision = '71e8ce0fb927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.TEXT(length=10),
               type_=sa.Text(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.Text(length=200),
               type_=sa.TEXT(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
