"""update table Users, change dtype passwords to textcol 200.

Revision ID: 71e8ce0fb927
Revises: 8fce2ac9fc2d
Create Date: 2023-10-07 21:26:52.737987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e8ce0fb927'
down_revision = '8fce2ac9fc2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.TEXT(length=10),
               type_=sa.Text(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.Text(length=200),
               type_=sa.TEXT(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
